apiVersion: v1
kind: Secret
metadata:
	name: example-secret
	labels:
		app: example-nginx
type: Opaque
data:
	# username: 'admin' -> base64: YWRtaW4=
	username: YWRtaW4=
	# password: 's3cr3t' -> base64: czNjcjN0
	password: czNjcjN0

